import { replacer as replacer$0 } from "../../util/utils.js";
/*
Copyright (c) 2012, Guillaume Marty

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
'use strict';
/**
 * A transliteration of Katakana & Hiragana to roman characters using the
 * modified Hepburn system.
 * Rules based on CLDR transform rule set `Katakana-Latin-BGN.xml` but with
 * several bugs fixed:
 *  * Missing ū
 *  * Missing tsu + voiced kana
 *  * typos on my~ transliterations
 *  * support for long vowel sign
 *  * support for final small tsu
 *  * support for u + small vowels
 *  * support for su/shi/ji + small vowels
 *  * support for tchi/tsu/te/to + small vowels
 *  * support for fu + small vowels
 *  * support for katakana middle dot
 *
 * \@todo Take iteration marks into account.
 */
const replacer = { replacer: replacer$0 }.replacer;
const transliterationTable1 = {
    ウァ: 'wa',
    ウィ: 'wi',
    ウェ: 'we',
    ウォ: 'wo',
    ウー: 'ū',
    ヴァ: 'va',
    ヴィ: 'vi',
    ヴェ: 've',
    ヴォ: 'vo',
    ヴュ: 'vyu',
    うぁ: 'wa',
    うぃ: 'wi',
    うぇ: 'we',
    うぉ: 'wo',
    うー: 'ū',
    ゔぁ: 'va',
    ゔぃ: 'vi',
    ゔぇ: 've',
    ゔぉ: 'vo',
    ゔゅ: 'vyu' // HIRAGANA LETTER VU + SMALL YU
};
const transliterationTable2 = {
    イェ: 'ye',
    ア: 'a',
    イ: 'i',
    ウウ: 'ū',
    ウ: 'u',
    エ: 'e',
    オウ: 'ō',
    オ: 'o',
    クァ: 'kwa',
    クィ: 'kwi',
    クェ: 'kwe',
    クォ: 'kwo',
    カ: 'ka',
    キョウ: 'kyō',
    キュウ: 'kyū',
    キャ: 'kya',
    キョ: 'kyo',
    キュ: 'kyu',
    キ: 'ki',
    ク: 'ku',
    ケ: 'ke',
    コウ: 'kō',
    コ: 'ko',
    シェ: 'she',
    スィ: 'si',
    サ: 'sa',
    ショウ: 'shō',
    シュウ: 'shū',
    シャ: 'sha',
    ショ: 'sho',
    シュ: 'shu',
    シ: 'shi',
    スウ: 'sū',
    ス: 'su',
    セ: 'se',
    ソウ: 'sō',
    ソ: 'so',
    チェ: 'che',
    ツァ: 'tsa',
    ツィ: 'tsi',
    ツェ: 'tse',
    ツォ: 'tso',
    ティ: 'ti',
    ディ: 'di',
    テュ: 'tyu',
    デュ: 'dyu',
    トィ: 'twi',
    トゥ: 'tu',
    ドィ: 'dwi',
    ドゥ: 'du',
    タ: 'ta',
    チョウ: 'chō',
    チュウ: 'chū',
    チャ: 'cha',
    チョ: 'cho',
    チュ: 'chu',
    チ: 'chi',
    ツウ: 'tsū',
    ツ: 'tsu',
    テ: 'te',
    トウ: 'tō',
    ト: 'to',
    ナ: 'na',
    ニョウ: 'nyō',
    ニュウ: 'nyū',
    ニャ: 'nya',
    ニョ: 'nyo',
    ニュ: 'nyu',
    ニ: 'ni',
    ヌウ: 'nū',
    ヌ: 'nu',
    ネ: 'ne',
    ノウ: 'nō',
    ノ: 'no',
    ファ: 'fa',
    フィ: 'fi',
    // 'フゥ': 'fu', // KATAKANA LETTER HU + SMALL U
    フェ: 'fe',
    フォ: 'fo',
    フュ: 'fyu',
    ホェ: 'hwe',
    ハ: 'ha',
    ヒョウ: 'hyō',
    ヒュウ: 'hyū',
    ヒャ: 'hya',
    ヒョ: 'hyo',
    ヒュ: 'hyu',
    ヒ: 'hi',
    フウ: 'fū',
    フ: 'fu',
    ヘ: 'he',
    ホウ: 'hō',
    ホ: 'ho',
    マ: 'ma',
    ミョウ: 'myō',
    ミュウ: 'myū',
    ミャ: 'mya',
    ミョ: 'myo',
    ミュ: 'myu',
    ミ: 'mi',
    ムウ: 'mū',
    ム: 'mu',
    メ: 'me',
    モウ: 'mō',
    モ: 'mo',
    ヤ: 'ya',
    ユウ: 'yū',
    ユ: 'yu',
    ヨウ: 'yō',
    ヨ: 'yo',
    リェ: 'rye',
    ラ: 'ra',
    リョウ: 'ryō',
    リュウ: 'ryū',
    リャ: 'rya',
    リョ: 'ryo',
    リュ: 'ryu',
    リ: 'ri',
    ルウ: 'rū',
    ル: 'ru',
    レ: 're',
    ロウ: 'rō',
    ロ: 'ro',
    ワ: 'wa',
    ヰ: 'i',
    ヱ: 'e',
    ヲ: 'o',
    ン: 'n',
    グァ: 'gwa',
    グィ: 'gwi',
    グェ: 'gwe',
    グォ: 'gwo',
    ガ: 'ga',
    ギョウ: 'gyō',
    ギュウ: 'gyū',
    ギャ: 'gya',
    ギョ: 'gyo',
    ギュ: 'gyu',
    ギ: 'gi',
    グウ: 'gū',
    グ: 'gu',
    ゲ: 'ge',
    ゴウ: 'gō',
    ゴ: 'go',
    ジェ: 'je',
    ズィ: 'zi',
    ザ: 'za',
    ジョウ: 'jō',
    ジュウ: 'jū',
    ジャ: 'ja',
    ジョ: 'jo',
    ジュ: 'ju',
    ジ: 'ji',
    ズウ: 'zū',
    ズ: 'zu',
    ゼ: 'ze',
    ゾウ: 'zō',
    ゾ: 'zo',
    ダ: 'da',
    ヂ: 'ji',
    ヅウ: 'zū',
    ヅ: 'zu',
    デ: 'de',
    ドウ: 'dō',
    ド: 'do',
    ブュ: 'byu',
    バ: 'ba',
    ビョウ: 'byō',
    ビュウ: 'byū',
    ビャ: 'bya',
    ビョ: 'byo',
    ビュ: 'byu',
    ビ: 'bi',
    ブウ: 'bū',
    ブ: 'bu',
    ベ: 'be',
    ボウ: 'bō',
    ボ: 'bo',
    パ: 'pa',
    ピョウ: 'pyō',
    ピュウ: 'pyū',
    ピャ: 'pya',
    ピョ: 'pyo',
    ピュ: 'pyu',
    ピ: 'pi',
    プウ: 'pū',
    プ: 'pu',
    ペ: 'pe',
    ポウ: 'pō',
    ポ: 'po',
    ヴ: 'v',
    '・': ' ',
    いぇ: 'ye',
    あ: 'a',
    い: 'i',
    うう: 'ū',
    う: 'u',
    え: 'e',
    おう: 'ō',
    お: 'o',
    くぁ: 'kwa',
    くぃ: 'kwi',
    くぇ: 'kwe',
    くぉ: 'kwo',
    か: 'ka',
    きょう: 'kyō',
    きゅう: 'kyū',
    きゃ: 'kya',
    きょ: 'kyo',
    きゅ: 'kyu',
    き: 'ki',
    くう: 'kū',
    く: 'ku',
    け: 'ke',
    こう: 'kō',
    こ: 'ko',
    しぇ: 'she',
    すぃ: 'si',
    さ: 'sa',
    しょう: 'shō',
    しゅう: 'shū',
    しゃ: 'sha',
    しょ: 'sho',
    しゅ: 'shu',
    し: 'shi',
    すう: 'sū',
    す: 'su',
    せ: 'se',
    そう: 'sō',
    そ: 'so',
    ちぇ: 'che',
    つぁ: 'tsa',
    つぃ: 'tsi',
    つぇ: 'tse',
    つぉ: 'tso',
    てぃ: 'ti',
    でぃ: 'di',
    てゅ: 'tyu',
    でゅ: 'dyu',
    とぃ: 'twi',
    とぅ: 'tu',
    どぃ: 'dwi',
    どぅ: 'du',
    た: 'ta',
    ちょう: 'chō',
    ちゅう: 'chū',
    ちゃ: 'cha',
    ちょ: 'cho',
    ちゅ: 'chu',
    ち: 'chi',
    つう: 'tsū',
    つ: 'tsu',
    て: 'te',
    とう: 'tō',
    と: 'to',
    な: 'na',
    にょう: 'nyō',
    にゅう: 'nyū',
    にゃ: 'nya',
    にょ: 'nyo',
    にゅ: 'nyu',
    に: 'ni',
    ぬう: 'nū',
    ぬ: 'nu',
    ね: 'ne',
    のう: 'nō',
    の: 'no',
    ふぁ: 'fa',
    ふぃ: 'fi',
    // 'ふぅ': 'fu', // HIRAGANA LETTER HU + SMALL U
    ふぇ: 'fe',
    ふぉ: 'fo',
    ふゅ: 'fyu',
    ほぇ: 'hwe',
    は: 'ha',
    ひょう: 'hyō',
    ひゅう: 'hyū',
    ひゃ: 'hya',
    ひょ: 'hyo',
    ひゅ: 'hyu',
    ひ: 'hi',
    ふう: 'fū',
    ふ: 'fu',
    へ: 'he',
    ほう: 'hō',
    ほ: 'ho',
    ま: 'ma',
    みょう: 'myō',
    みゅう: 'myū',
    みゃ: 'mya',
    みょ: 'myo',
    みゅ: 'myu',
    み: 'mi',
    むう: 'mū',
    む: 'mu',
    め: 'me',
    もう: 'mō',
    も: 'mo',
    や: 'ya',
    ゆう: 'yū',
    ゆ: 'yu',
    よう: 'yō',
    よ: 'yo',
    りぇ: 'rye',
    ら: 'ra',
    りょう: 'ryō',
    りゅう: 'ryū',
    りゃ: 'rya',
    りょ: 'ryo',
    りゅ: 'ryu',
    り: 'ri',
    るう: 'rū',
    る: 'ru',
    れ: 're',
    ろう: 'rō',
    ろ: 'ro',
    わ: 'wa',
    ゐ: 'i',
    ゑ: 'e',
    を: 'o',
    ん: 'n',
    ぐぁ: 'gwa',
    ぐぃ: 'gwi',
    ぐぇ: 'gwe',
    ぐぉ: 'gwo',
    が: 'ga',
    ぎょう: 'gyō',
    ぎゅう: 'gyū',
    ぎゃ: 'gya',
    ぎょ: 'gyo',
    ぎゅ: 'gyu',
    ぎ: 'gi',
    ぐう: 'gū',
    ぐ: 'gu',
    げ: 'ge',
    ごう: 'gō',
    ご: 'go',
    じぇ: 'je',
    ずぃ: 'zi',
    ざ: 'za',
    じょう: 'jō',
    じゅう: 'jū',
    じゃ: 'ja',
    じょ: 'jo',
    じゅ: 'ju',
    じ: 'ji',
    ずう: 'zū',
    ず: 'zu',
    ぜ: 'ze',
    ぞう: 'zō',
    ぞ: 'zo',
    だ: 'da',
    ぢ: 'ji',
    づう: 'zū',
    づ: 'zu',
    で: 'de',
    どう: 'dō',
    ど: 'do',
    ぶゅ: 'byu',
    ば: 'ba',
    びょう: 'byō',
    びゅう: 'byū',
    びゃ: 'bya',
    びょ: 'byo',
    びゅ: 'byu',
    び: 'bi',
    ぶう: 'bū',
    ぶ: 'bu',
    べ: 'be',
    ぼう: 'bō',
    ぼ: 'bo',
    ぱ: 'pa',
    ぴょう: 'pyō',
    ぴゅう: 'pyū',
    ぴゃ: 'pya',
    ぴょ: 'pyo',
    ぴゅ: 'pyu',
    ぴ: 'pi',
    ぷう: 'pū',
    ぷ: 'pu',
    ぺ: 'pe',
    ぽう: 'pō',
    ぽ: 'po',
    ゔ: 'v' // HIRAGANA LETTER VU
};
const transliterationTable3 = {
    aァ: 'ā',
    aぁ: 'ā',
    iィー: 'ī',
    iィ: 'ī',
    iぃー: 'ī',
    iぃ: 'ī',
    aー: 'ā',
    iー: 'ī',
    uー: 'ū',
    eー: 'ē',
    oー: 'ō',
    // Fallback for small vowels
    ァ: 'a',
    ィ: 'i',
    ゥ: 'u',
    ェ: 'e',
    ォ: 'o',
    ぁ: 'a',
    ぃ: 'i',
    ぅ: 'u',
    ぇ: 'e',
    ぉ: 'o'
};
const replace1 = replacer(transliterationTable1);
const replace2 = replacer(transliterationTable2);
const replace3 = replacer(transliterationTable3);
export default (function (str) {
    str = replace1(str);
    str = str
        .replace(/ッ(?=[ン])/g, 'n') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[ん])/g, 'n') // HIRAGANA LETTER SMALL TU
        .replace(/ン(?=[バビブベボパピプペポマミムメモ])/g, 'm') // KATAKANA LETTER N
        .replace(/ん(?=[ばびぶべぼぱぴぷぺぽまみむめも])/g, 'm') // HIRAGANA LETTER N
        .replace(/ン(?=[ヤユヨアイウエオ])/g, "n'") // KATAKANA LETTER N
        .replace(/ん(?=[やゆよあいうえお])/g, "n'"); // HIRAGANA LETTER N
    str = str
        .replace(/ッ(?=[カキクケコ])/g, 'k') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[かきくけこ])/g, 'k') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ガギグゲゴ])/g, 'g') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[がぎぐげご])/g, 'g') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[サシスセソ])/g, 's') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[さしすせそ])/g, 's') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ザズゼゾ])/g, 'z') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[ざずぜぞ])/g, 'z') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ジ])/g, 'j') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[じ])/g, 'j') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[タチツテト])/g, 't') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[たちつてと])/g, 't') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ダヂヅデド])/g, 't') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[だぢづでど])/g, 't') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ハヒヘホ])/g, 'h') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[はひへほ])/g, 'h') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[フ])/g, 'f') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[ふ])/g, 'f') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[バビブベボ])/g, 'b') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[ばびぶべぼ])/g, 'b') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[パピプペポ])/g, 'p') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[ぱぴぷぺぽ])/g, 'p') // HIRAGANA LETTER SMALL TU
        .replace(/ッ(?=[ラリルレロ])/g, 'r') // KATAKANA LETTER SMALL TU
        .replace(/っ(?=[らりるれろ])/g, 'r'); // HIRAGANA LETTER SMALL TU
    str = replace2(str);
    str = replace3(str);
    str = str
        .replace(/(ッ|っ)\B/g, 't'); // FINAL KATAKANA LETTER SMALL TU
    return str;
});
